name: Docker Image CI

on:
  push:
    tags: 
      - v*

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: ${GITHUB_REF/refs\/tags\//} 
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jphuc96/kubectl:${DOCKER_TAG} --tag jphuc96/kubectl:latest
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSEWORD }}
    - name: Push image
      run: docker push jphuc96/kubectl:${DOCKER_TAG} && docker push jphuc96/kubectl:latest     
